### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by aradi** [subugoe/typo3-bib#32]
It would be fantastic, if the extension would work when Typo3 is run under PHP 7, as most Linux distributions ship it now as default PHP version. Currently, the version in TER indicates PHP 5 compatibility only.

**Comment by ipf** [comment]
Hi, that would indeed be nice. Could you maybe test that and report it?
I am not aware of any 'gems' that could avoid running this in PHP7. The dependency was only added, because PHP7 was not released at that time and so couldn't easily be tested.

**Comment by aradi** [comment]
Sure, I'll try it later this week and let you know.

**Comment by aradi** [comment]
After removing the constraint on PHP from the package, I could install it without any problems in Typo 3 7.6 with PHP 7. It definitely shows the correct publication lists (filtered and unfiltered). I did not check adding publications so far, but I guess, it would then work as well.

**Comment by ipf** [comment]
Thanks for testing and reporting!
